### ISSUE TITLE
[ic-top-navigation] Update component undefined error to show if both app title slot and prop haven't been used

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1294]
## Summary of the bug 
Currently if a user slots in a link to the app title of top navigation then there are errors saying that an app title is required as they haven't used the prop. This should be updated to only show if the slot or prop haven't been used.

There should also be an update to the prop and/or slot description to say that one or the other has to be used. 

## 🧐 Expected behaviour 
Component undefined error should only show if neither the app title slot or prop has been used.

## Additional info 
It does currently have the following code, so I'd have expected it to already have this functionality. But errors may just be slipping through in some places, so worth investigating alongside the prop/slot description update.
```
!isSlotUsed(this.el, "app-title") &&
      onComponentRequiredPropUndefined(
        [{ prop: this.appTitle, propName: "app-title" }],
        "Top Navigation"
      );
```

**Comment by GCHQ-Developer-257** [comment]
Have been looking into this problem recently and believe it is a gatsby prerendering issue. 

After testing of the componentDidLoad function, including rewriting it to assert against latency issues and utilising the recent waitForHydration function, I do believe the function is performing and being triggered appropriately. 

As the error only appears in the local build of the design site and not in the browser console, I think it is due to the gastby pre-rendering where the inner component holding the slot="app-title" is not available in build.
