### ISSUE TITLE
Explore visual testing for FOUC

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#1415]
## Summary 
Explore visual testing for FOUC (Flicker Of Unstyled Content)

## 💬 Description 
Explore if we can utilise Cypress to take a visual test before and after hydration, and if that will be any use in preventing the various bugs that have been raised. If it is simple to add, this can include the addition of the changes.

Some of the bugs reported:
- #1216 
- #1409 
- #1408 
- #1410 

## 💰 User value 
Prevent the FOUC before the user has to report it.

**Comment by GCHQ-Developer-847** [comment]
The FOUC issues on the website are no longer visible due to the Gatsby plugin (`gatsby-plugin-fix-fouc`) which has been added. We have agreed that this ticket (and all of those mentioned in the description) can be closed now because of this. 

If any customers have a Gatsby app and are experiencing similar FOUC issues, then it would be up to them to look at applying a similar fix as it is fundamentally a Gatsby problem, and the issues would happen with whichever component library they use.
