### ISSUE TITLE
Prepare and document for the v3 release

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#1516]
## Summary 
Prepare and document for the upcoming V3 release by addressing testing, progress towards feature parity, defining the scope of the version, the hosting strategy, git strategy and setting a release estimation.

## 💬 Description 
To ensure we have prepared for the V3 release, this issue should cover:

1. Testing: Ensure all components have plans to be tested against the DoD before v3, and these plans are in motion.
2. Feature parity: Ensure all components have feature parity with other component libraries customers may have used, and those plans are in motion.
3. Scope: Define the scope of v3 and what we aim to include in it. Clearly define what features and changes are included in V3, and what should be in subsequent versions such as V3.x. Breaking changes are essential for V3. GitHub milestones should be considered here.
4. Hosting strategy: Plan and break down how we plan to host both V2 and V3 versions of both the website and components concurrently. In terms of the component hosting, we will have a period of time where we do not want people to migrate to V3, but we do want it as a prerelease. 
5. Git strategy: Explore how we will keep our V2 and V3 changes in sync, for the period of time we are developing on both V2 and V3, if that is the plan. We will not want a whole PI of no release.
6. Release date estimation: Discuss and agree a specific PI (is it PI 8?) to release and coordinate with the rest of the team.

## 💰 Use value 
- Ensure a smooth release process for V3
- Provide a better quality product to our customers
- Achieve all the goals listed above

**Comment by MI6-255** [comment]
I have logged the branch and hosting strategy is stored in Figma under Development / Version 3 branch and release strategy. The rest of this can now be picked up by another member of the team.

**Comment by jd239** [comment]
Tasks which were mentioned during internal discussion:
- Turning user feedback obtained via interviews into tickets.
  - Tickets should be prioritised to provide a picture of what needs to be done before V3 and what can be done during v3
- Branching / Releasing / Hosting strategy
  - This is currrently WIP by @MI6-255 
- Test all components against the PR checklist
- Refactoring components to improve long term maintenance
  - Are there any components which are very complicated to maintain?
  - Does each component require the Shadow DOM
- Canary component move from Canary to Beta / Prod within core package
- Update or change dependencies
  - Are there any dependencies which can be removed or updated to new major versions
  - Does there need to be consideration for the output targets?
- Styling
  - Worth considering SASS due to the functionality it provides with regards to themeing and customisation
  - Can we still utilize our design tokens?
  - How does using SASS affect our workflow?
- Documentation
  - Review guidance site and make notes of any updates required.
  - Is it possible to add a component playground to the guidance site
- Migration
  - Look into using codemod to improve migration between V2 to V3
- Release date....
