### ISSUE TITLE
Investigate how to get badge screen reader functionality working for NVDA

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-ui-kit#1717]
## Summary 
Investigate what can be done to get the badge component's screen reader functionality working for NVDA.

## 💬 Description 
A colleague who is able to use NVDA has reported that there are some issues with the badge's accessible text - in that the aria-label that is added to the parent component is not being read out. Some improvements have been made as part of #1391, which have been tested with VoiceOver and all appears to work fine, but getting information about the badge to be read out by NVDA still seems to be a problem.

It has been difficult to test different solutions due to NVDA being software that is only available on a Windows device. This separate ticket has been created for this reason; it is best if someone who has NVDA on their device can pick this up to make it easier to find a solution. It's possible that it is an NVDA bug.

**Note:** I added some information to the [description for my PR](https://github.com/mi6/ic-ui-kit/pull/1682) which may help, e.g. the code which will allow you to display all possible parent components for a badge on one page for easier testing.

## 💰 User value 
This will ensure that NVDA users can hear information about badges just like VoiceOver users can.

## 📚 User Stories 
*As a* screen reader user who uses NVDA
*I need* to be able to hear all the accessible text for badge components that VoiceOver users can
*So that* I can fully understand that a badge is being displayed and what it is representing.

**Comment by GCHQ-Developer-847** [comment]
It's important to ensure that the badge label doesn't override any aria-label that might exist on the parent component.

Also, any changes you make to get NVDA working will need to of course still work with VoiceOver so would be good to get a VoiceOver user to test (if you don't have VoiceOver).

**Comment by GCHQ-Developer-299** [comment]
Gotten around to testing this, interestingly even in Voiceover the "with badge being displayed" accessible text is not read out on badges with `text-label`.
In NVDA, you can use up/down arrows to navigate to badges, and at least on buttons the order is 1: badge 2: button so it's not entirely inaccessible. At the very least I want to make sure all types of badge read the "with badge" text on voiceover, and then get that being read out in NVDA too. Maybe there's some way to change how the badge slot works and instead of adding an aria-label we hide some sr-only text with the full badge text in it?
