### ISSUE TITLE
[tabs]: Dynamically generating tabs produces unusual behaviour

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#1799]
## Summary of the bug 
Dynamically generating tabs produces the following issues:
- Tab panel appears above the tabs
- The first tab is not selected
- If the second tab is selected and another tab is dynamically removed, the second tab loses the selected state and the first tab is selected
- All tabPanels are displayed when tabs are dynamically loaded and a tab is selected

## 🪜 How to reproduce 
See below

## 📸 Screenshots or code 
Code example which can be added to Stackblitz or application to reproduce:

Link to stackblitz: https://stackblitz.com/edit/vitejs-vite-ywsvuc?file=src%2FApp.tsx

## 🖥 📱 Device 
- Type: Desktop
- Device: Windows 
- OS version: N/A
- Browser version: Chrome 122

## 🧐 Expected behaviour 
- The tab panel should appear below the tabs
- The first tab should be selected when dynamically adding all tabs
- Only selected tab panel should appear

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil. 

*Given the tabs has no data* 
*When I add tabs dynamically*  
*Then the first tab should appear selected with the corresponding tab panel appearing underneath* 

## Additional info 
Tell us anything else useful to help us fix or understand the problem.

**Comment by GCHQ-Developer-741** [comment]
Work has been done on the linked branch to address the issues. Currently fixed the first tab not selecting, and the issue around the second tab losing selection during removal could not be replicated. The other two issues are still outstanding.

**Comment by GCHQ-Developer-299** [comment]
Regarding the first issue "Tab panel appears above the tabs" I think this is because IcTabContext doesn't mandate the order in which its child components are rendered (i don't know much about slots) 

I stuck a couple of <p> tags between the Group and Panels and it ended up sandwiching the panels:
![Image](https://github.com/user-attachments/assets/ae9eaa8c-da00-44d4-ba30-4856face924a)

So i think the solution to this might be specifying TabContext's child slots, but that would be a breaking change...  will see if I can solve this by just modifying the Dynamic Rendering story

**Comment by GCHQ-Developer-299** [comment]
Regards "All tabPanels are displayed when tabs are dynamically loaded and a tab is selected"
it seems that every not-yet-displayed tab gets displayed when you click a new tab. This makes me think that when a tab is dynamically added, some field isn't set right to make it hidden when `configureTabs()` fires. Looking into it.

I solved "Tab panel appears above the tabs" by adding an empty span inside the tab context. Bit of a botch but it *is* a solution without a breaking change.
