### ISSUE TITLE
IcDataTable type error

### ISSUE THREAD

**Issue by MI6-651** [mi6/ic-ui-kit#2091]
I get the error "string is not assignable to type 'IcDataTableColumnDataTypes'", even though looking through the code, strings are part of the union type. It would also be nice to export all types for components, this would follow convention with other libraries. Currently 'IcDataTableColumnDataType' cannot be imported.

**Comment by GCHQ-Developer-530** [comment]
All types for components can be imported from @ukic/web-components

**Comment by GCHQ-Developer-741** [comment]
Hello, hoping to clear up any confusion. `IcDataTableColumnDataTypes` contains 5 different string values: `"string"`, `"number"`, `"address"`, `"element"`, `"date"`, rather than allowing any value of type string, as you mentioned in the description for example.

The purpose of this is so the data table component can understand and correctly render data differently depending on what it is, by limiting the potential inputs to ones we can account for. If a user creates an address column:
```ts
const columns: IcDataTableColumnObject[] = [
  {
    key: "homeAddress",
    title: "Home Address",
    dataType: "address"
  }
]
```
then the dataType value will know to render that column in the address format.

So when using this type to define a variable, that variable can only be set to one of those 5 values:
```ts
const x: IcDataTableColumnDataTypes = "string" //correct
const x: IcDataTableColumnDataTypes = "address" //correct
const x: IcDataTableColumnDataTypes = "a custom string" //incorrect
```

Hope this helps. As for the type exporting, that is being done in https://github.com/mi6/ic-ui-kit/pull/2401
