### ISSUE TITLE
[ic-select] Add ability to pass in custom select items to select component

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#224]
## Summary
Allow for users to customise their select items to not just be text, e.g. adding a status tag to some of the options.

## 💰 Use value
Would allow users to pass in their own component into each of the drop down items.

**Comment by GCHQ-Developer-847** [comment]
Two potential solutions for this:

1. Add a property to the IcMenuOption object to which the user can pass custom HTML (a bit like the `actions` property of the data table)

2. Create a new component for the select options (e.g. something like `<IcMenuItem>`) and refactor ic-menu and ic-select to allow users to slot these options into the select (similar to [MUI](https://mui.com/material-ui/react-select/#basic-select)) instead of passing the options as an array to the `options` prop

Option 1 would of course be a lot quicker and easier to implement and the avoid the breaking change of Option 2, but it would allow less flexibility / customisation. Although with Option 1, we could allow for a bit of flexibility about where the custom HTML element is placed by maybe adding another property which determines whether the element is placed to the left or the right of the option text.

**Comment by DBD324** [comment]
Figma updated to include new icon option in select droplist menu options. #1034
