### ISSUE TITLE
Multi-select

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#257]
## Summary
Multi-select dropdowns allow users to select multiple values from a list of one or more options.

## 💬 Description
*As a* developer
*I need* a multi-select dropdown component
*So that* I can build rich applications.

*As a* ICDS user 
*I need* to be set the size property on a multi-select:
- Size: Default, Small, Large
*So that* I can use it in applications with different layout densities. 

*As a* ICDS user
*I need* the following droplist variations:
- Sectioned
- Recommended
- With icon
*So that* I can organise the select options. 

## 💰 Use value
Foundational component required to provide ICDS users the tools to build rich applications.

## Acceptance criteria

**Properties**
*Given* that a multi-select is being implemeneted
*When* settings its properties
*Then* a size property can be used to set its size to default, small or large. 

**Disabled**
~~*Given* that a multi-select exists on a page and is disabled
*When* moving focus to it,
*Then* it should still be announced by a SR, but also indicated as disabled
*and* the droplist should not be able to be opened.~~

*Given* that a multi-select's options are being set up
*When* setting option properties
*Then* an option can be set to disabled resulting in it becoming non-selectable and causing it show its disabled styling. 

**Focus, mouse interaction and keyboard controls**
*Given* that a multi-select exists on a page 
*When* I click on the field, 
*Then* the droplist is displayed and focussed.

*Given* that a multi-select exists on a page,
*When* I 'tab' to the field,
*Then* the field should be focussed, 
*And* the droplist should NOT immediately display. 

*Given* that focus is applied to a multi-select input
*When* I use the 'enter' or 'space' keys, or click on the field
*Then* the droplist should open with focus applied to the droplist. 

*Given* that focus is applied to the droplist attached to a multi-select input
*When* I use the 'up/down' keys 
*Then* the options should be focussed in order in the direction of the arrow keys. 

~~*Given* that focus is applied to the droplist attached to a multi-select input
*When* I use the 'up/down' keys, and hold 'shift'
*Then* the options should be focussed in order in the direction of the arrow keys,
*And* the option should automatically be selected/deselected.~~

~~*Given* that focus is applied to the droplist attached to a mutli-select input
*When* an option is selected (by mouse or keyboard) while holding the 'shift' key
*Then* all contiguous options between the current option and the last selected option should be selected.~~

*Given* that focus is applied to the droplist attached to a multi-select input
*When* I use the 'home' key
*Then* the first option in the list should be focussed. 

*Given* that focus is applied to the droplist attached to a multi-select input
*When* I use the 'end' key
*Then* the last option in the list should be focussed. 

~~*Given* that focus is applied to an option in an expanded droplist
*When* using the key combination 'ctrl+shift+home'
*Then* all options from the current option to the first option in the list should be selected.~~

~~*Given* that focus is applied to an option in an expanded droplist
*When* using the key combination 'ctrl+shift+end'
*Then* all options from the current option to the last option in the list should be selected.~~

*Given* that a multi-select exists on a page, and the droplist is focussed
*When* I click outside of the field or droplist, but not on another focussable element
*Or* when I use the 'esc' key, 
*Then* the droplist is hidden, but the field remains focussed. 

*Given* that a multi-select droplist is focussed, 
*And* the 'select all' or 'hide all' button is present
*When* I tab onwards
*Then* the 'select all' or 'hide all' button should be focussed. 

*Given* that a multi-select droplist is expanded and focussed, and not all options are selected
*When* using the keyboard combination 'Ctrl+a', 
*Then* all options should become selected, 
*And* the multi-select field should update to show all selections, 
*And* the number selected label should update to show all selected, 
*And* the select all button should change to 'clear all',
*And* the droplist should remain open, 
*And* focus should remain where it was. 

*Given* that a multi-select droplist is expanded and focussed, and all options are selected
*When* using the keyboard combination 'Ctrl+a', 
*Then* all options should become de-selected, 
*And* the multi-select field should update to show its placeholder, 
*And* the number selected label should update to show none selected, 
*And* the clear all button should change to 'select all',
*And* the droplist should remain open, 
*And* focus should remain where it was. 

*Given* that a multi-select exists on a page, the droplist is closed, no selections are made, and the field is focussed
*When* I tab onwards, or shift tab backwards
*Then* the next, or previous, focussable element should become focussed. 

*Given* that a multi-select exists on a page, the droplist is closed, some selections are made, and the field is focussed
*When* I tab onwards,
*Then* the inline clear button (x) should be focussed. 

**Selection**
*Given* that a multiselect droplist is expanded
*When* an option is clicked, or if 'enter' or 'space' key is pressed whilst it is focussed
*Then* the option should be selected/deselected, 
*And* the field should update to show the change in selection, 
*And* the number selected label should update, 
*And* the droplist should remain open,  
*And* focus should remain on the option. 

*Given* that a multi-select droplist is expanded, and an option has already been selected from the list
*When* an additional option in the droplist is selected,
*Then* the multi-select field should update, adding the new option to the currently selected list
*And* it should appear in the list based on the order of the options in the droplist. 
E.g, A multiselect list allows selection of multiple countries in alphabetical order. 
The first selection is Chile. The multiselect field should read "Chile".
The second selection is then Botswana. The multiselect field should read "Botswana, Chile".

*Given* that I can make multiple selections
*And* there isn’t enough space to visually show all my selections
*When* I select an additional option in the droplist
*Then* the select field input should update, adding the option to the currently selected options, truncating the end of the string.

**Clear**
*Given* that a multi-select exists with options selected, 
*When* focussing on the field,
*Then* a clear icon button should appear in the field, 
*And when* clicked, 
*Then* all selected options should be cleared. 

**Selection bar**
*Given* that a multi-select exists, is focussed, and the droplist is open, 
*When* viewing the droplist
*Then* a selection bar is displayed at the top of the list. 

*Given* that a selection bar is present
*When* the option list is scrolled
*Then* the selection bar should remain stuck to the top of the window. 

*Given* that a selection bar is present, and not all items are selected
*When* displayed, 
*then* a 'select all' button should appear on the right-hand side. 

*Given* that a selection bar is present, and all items are selected
*When* displayed, 
*then* a 'clear-all' button should appear on the right-hand side in place of the select all button.

*Given* that the 'select all' button is displayed
*When* it is clicked, or if the 'enter' or 'space' key is pressed whilst it is focussed, 
*Then* all options should be selected in the droplist, the field should update to show all selected options, the 'select all' button should change to 'hide all', and focus should be returned to the droplist. 

*Given* that the 'hide all' button is displayed
*When* it is clicked, or if the 'enter' or 'space' key is pressed whilst it is focussed, 
*Then* all options should be de-selected in the droplist, the field should update to show its unselected state, the 'hide all' button should change to 'select all', and focus should be returned to the droplist. 

*Given* that a selection bar is present
*When* the number of selected items is changed
*Then* the selection indicator label should update to show the currently selected number of items. 
*And* this change should be announced by a screen reader. 

**Validation**
*Given* that a multi-select is being implemented
*When* setting its properties
*Then* validation messages can be customised for different use cases. 
For example, on submit of a form, a developer may want to show a custom validation message next to the field. 

*Given* that a multi-select is being implemented
*When* setting it properties
*Then* the validation status can be set to either error, warning, or success. 

**Sizing**
*Given* that a multi-select is being implemented
*When* specifying its width, 
*Then* the field can be set to any width, but the droplist can't be smaller than the minimum width (304px)

*Given* that a multi-select is being implemented
*When* setting its height to a value smaller than is able to display all select options, 
*Then* the option list should be scrollable and a scroll bar should display.

*Given* that a multi-select is being implemented, 
*When* setting its properties
*Then* its size can be set to either small, default or large. 

**Position**
*Given* that a multi-select exists on a page
*When* it is opened
*Then* the droplist should expand below the multi-select field, and overlay other content below it. 

*Given* that a multi-select exists on a page, and not enough space is available below to display the option list
*When* it is opened
*Then* the droplist should expand above the multi-select field, and overlay other content below it. 

**Drop list options**

*Given* that a multiselect droplist is being set up
*When* specifying its options
*Then* it can be set to also show groups of options in the droplist, titled by a group label. 

*Given* that a multiselect droplist is being set up
*When* specifying it options
*Then* recommended options can be set to appear at the top of the list, separated from other options by a line divider.

~~*Given* that a multiselect droplist is being setup
*When* setting its properties
*Then* an option is available to change the presentation of its options between the following:
- Default: Label only, and a right aligned checkmark displays the selection state. 
- Checkboxes: A checkbox is rendered in front of the labelling and is what displays the selection state.~~

**Empty and loading states**

*Given* that a droplist is loading its contents
*When* the loading prop is set to true
*Then* the loading state should display.

*Given* that a droplist load failed
*When* it is opened
*Then* the loading error state should display. 

*Given* that a droplist has no loaded options
*When* it is opened
*Then* its empty state should display. 

**Screen reader**

*Given* that an enabled multiselect field exists on page, with no options selected
*When* navigated to by a screen reader
*Then* the following should be announced:
- Field label
- Helper text (if present)
- Placeholder text
- Details about list box. 
- Validation message (if present)

*Given* that an enabled multiselect field exists on page, with some options selected
*When* navigated to by a screen reader
*Then* the following should be announced:
- Field label
- Helper text (if present)
- Number of items selected out of total number of items (e.g 4 of 8 selected)
- Input label (e.g Australia, Bahamas, Cuba, Denmark)
- Details about list box. 
- Validation message (if present)

*Given* that an enabled multiselect field exists on a page, and the droplist is open
*When* navigating between each option using a SR
*Then* the following should be announced:
- Option label
- Selection status
- Option number (eg 1 of 8)

*Given* that an enabled multiselect field exists on a page, and the droplist is open
*When* selecting/deselecting each option using a SR
*Then* the following should be announced:
- Option label
- Selection status
- Option number (eg 1 of 8)
- Total selected (eg 2 of 8 selected)

*Given* that a mutli-select droplist contains a disabled option
*When* navigating via a SR
*Then* it should be navigable and should announce as inactive. 

**Animation**
*Given* that a mutli-select exists
*When* opened or closed
*Then* the same animation settings as select boxes, date pickers and other dropdown inputs should be used. 

*Given* that a multi-select exists, and user has set the 'prefers-reduced-motion' option on their browser, 
*When* the multi-select is opened or closed
*Then* no animation should occur and the droplist should open/close instantaneously

**Comment by MI6-255** [comment]
Links to #666, we have agreed we can do this work without doing 666 first, however, we need to make this addition it's own component, so it doesn't make the problem bigger. Possibly add this variant as a sub component, that is imported behind the scenes

**Comment by GCHQ-Developer-847** [comment]
Tooltip AC has been moved to #1109

**Comment by GCHQ-Developer-847** [comment]
About the AC to do with having checkboxes on options - spoken to a designer and we don't want this so just ignore

**Comment by GCHQ-Developer-299** [comment]
Still to do as of 28/09:

- No results state. This needs to exist on all 3 variants (single, searchable, multi) - if an empty array is passed to the options prop, it should show this empty state - maybe add stories to each 
- Add a story demonstrating the loading error state to single, searchable, and multi selects (Can see this and the no results state in the Atoms page in Figma). This already exists on ic-menu (can see it on search bar ‘External filtering with loading’ story) - just need to allow it on the selects, and demonstrate it in the stories
- Some of the AC mention using keyboard combinations - the two about the ‘Ctrl+A’ one have been done, but the ones about ‘Ctrl+Shift+End’, ‘Ctrl-Shift+Home’ and ‘Up\down keys + Shift’ have not. These are based on the [W3C guidance for listboxes](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/#:~:text=of%20characters%20typed.-,Multiple%20Selection,-%3A%20Authors%20may%20implement) but because they are listed there as being optional - if it turns out to be difficult, they can be separated out into another ticket and done later

 
Screen reader issues / tasks:
 

- Problem with screen reader not focusing on options has been half fixed by adding menu.tabindex and the ‘setAttribute(“aria-activedescendant”)’s (turns out that aria-activedescendant can actually affect focus: [https://zellwk.com/blog/element-focus-vs-aria-activedescendant/](https://zellwk.com/blog/element-focus-vs-aria-activedescendant/)). But if you open the select by pressing Enter, the options don’t get focussed until you actually select an option
- Also re-focuses on options that aren’t visually selected (should just be focused on whole menu) when you click on ‘Select all’ button - maybe look at removing ‘aria-activedescendant’ attribute on menu blur
- Could ‘preventMenuFocus’ be affecting things?
- Note: the reason for adding the menu.tabindex stuff is to ensure the menu itself is not focusable when we’re trying to focus on the options – I saw an article (can’t find it anymore) which says an element with role=”listbox” does not allow children to be focused on if it itself is focusable (has a tabindex of 0)
- Screen reader reads out ‘selected, selected’ or ‘not selected, selected’ for each option - don’t want that second ‘selected’
- Check the different screen reader AC on the ticket and make sure they’re all implemented
- Double-check no bugs have been introduced in the single select, searchable select and search bar
- Make sure all items in the new PR checklist have been checked
- Tests - write unit tests and try to get good coverage , update visual tests, add a11y unit test
- Check there are no lint warnings
- Add React stories
- Rebase from develop and squash commits

**Comment by GCHQ-Developer-847** [comment]
Because the "no results" state does not already exist on the single and searchable select, it has been moved out into a separate ticket (#1207) as it is a bigger issue than adding it only to the multi-select.

**Comment by GCHQ-Developer-847** [comment]
Some of the ACs for keyboard interaction in this ticket are described by W3C as optional - these have been separated out into another ticket ([#1277](https://github.com/mi6/ic-ui-kit/issues/1277)) so that they can be implemented at a later date and don't slow down the completion of the multi-select.

**Comment by GCHQ-Developer-847** [comment]
The multi-select’s screen reader behaviour was tested in a session with a user. There were some things to consider which came out of the session, including some questions / thoughts from a designer who also attended; I have been thinking about some answers / my opinions about these so wanted to note them all down here.


**Is the announcement sufficient in indicating that the select is open?**

The screen reader and focus behaviour of a lot of other examples of select components online does vary (e.g. moving focus only to options and never the whole menu, or even not moving focus at all automatically so the user has to tab to the dropdown menu), so it is difficult to say what the behaviour for the ic-select should be in terms of what feedback the user is getting from the screen reader. The `aria-expanded` attribute is changed to “true” when the select is opened, but the focus moves onto the menu which is why the screen reader does not say “expanded”.  I would personally say it’s sufficient as it is, though, as the screen reader clearly announces that the focus has moved onto a different element - from a button to a listbox. 


**Is the “7 of 7 selected” announcement sufficient to indicate the change?** 

When the user tabs onto the “Select all” button, the screen reader reads out “Select all options for <select label>” - so it is clear what will happen when they press the button. I think that this, in conjunction with the “7 of 7 selected” announcement, makes it clear enough that they are now all selected. 

The user from the session tends to use ‘Control + Option + Space’ to click on things. They tried it initially on the multi-select but it didn’t work.  I tried this myself after the session, also using VoiceOver and Edge and it opened the dropdown menu, so I am not sure why it didn’t work during the session. However, it doesn’t work on Safari (also tested with the single select), so I have [opened a ticket](https://github.com/mi6/ic-ui-kit/issues/1451) to explore why this is the case.


**How does the screen reader behave when there are a lot of options and you use the “Select all” button?**

Whatever the amount of options, it always announces a count of how many are selected e.g. “25 of 25 selected”. It also goes through the individual details of each option e.g. “Cappuccino selected, (1 of 14), Latte selected (2 of 14) … “, but it only does this when the amount of options is under 15. I would say that this is fine as it’s probably less likely you’ll want to hear about every individual option that is selected when there are a significant amount than when there are only a few. And you can always focus on each option to hear whether certain ones are selected.


**The user was happy with the clear button behaviour. Could it be improved further with an “input cleared” announcement?**

From a quick look, I have not found much guidance about this online, or any W3C examples with clearing functionality to test this, so I’m not sure what the best practice would be. However, the user hears the “Clear selection” label on the button, and after pressing it, it is clear that the focus moves back to the select, and the placeholder is also read out. Furthermore, in the session, the user felt it was easy enough to understand, so I think all these points suggest that the current behaviour is sufficient.  


**When focussed on the helper text variant, the screen reader says the word “description” before reading out the helper text. Is this needed?**

This is the built-in behaviour when using `aria-describedby`, which is the [recommended ARIA attribute](https://www.w3.org/TR/WCAG20-TECHS/ARIA1.html#:~:text=Example%202%3A-Using%20aria%2Ddescribedby%20to%20associate%20instructions%20with%20form%20fields-Sample%20form%20field) to use when providing additional instructions for form fields.


**There was some odd behaviour when using the arrow keys on the helper text variant, e.g. they didn’t open the dropdown menu.**

Not quite sure what happened here as the only difference with this variant and the default one is the helper text being displayed. I have tested the arrow keys with VoiceOver enabled and on Edge and it all works fine. They open the menu and focus on options as expected.


**On the disabled options variant, it would be clearer if the announcement says “1 of 7 selected” rather than “1 of 4 selected” i.e. out of the total number of options including the disabled ones.**

I will include this update in the “a11y” branch for the multi-select - i.e. it will be in the second PR that gets raised, which will contain all of the screen reader fixes.

**Comment by GCHQ-Developer-847** [comment]
Just wanted to gather all the comments about the AC in a single place: 

- As agreed with a designer, the multi-select matches the single and searchable selects with its disabled state in that it is not focussable, but if a screen reader user were to use the virtual cursor, it would be read out as being disabled.

- Spoke to a designer about allowing for checkboxes to be shown on options and we don’t want this feature anymore. (It could fit into the future work about allowing custom elements to be added to options).

- Tooltip AC has been moved to [#1109](https://github.com/mi6/ic-ui-kit/issues/1109).

- Some of the ACs for keyboard interaction in this ticket are described by W3C as optional - these have been separated out into another ticket ([#1277](https://github.com/mi6/ic-ui-kit/issues/1277)) so that they can be implemented at a later date and don't slow down the completion of the multi-select.
