### ISSUE TITLE
[ic-checkbox]: Update event.detail from `icChange` and `icCheck`

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#464]
## Summary
`icChange` which is emitted from `ic-checkbox-group` returns an array of `ic-checkbox` values. When checking and unchecking the checkboxes within the group, the same array is returned. Further work is required by the consumer to get the checked state of the checkboxes which, may not be necessary if more detail is returned from the event. This ticket is to add a checked object to the `icChange` event so that `ic-checkbox-group` returns an object which can be used directly. 

## 💬 Description
When logging the value detail from `icChange` on `IcCheckboxGroup`, an array of the enabled checkbox values are returned `['foo','bar']`. When an checkbox is unchecked, the `icChange` still emitts `['foo', 'bar']`. This information is emitted from the value `event.detail.value`. No detail about what has been unchecked/checked is provided by the event.

It's worthwhile returning an object which provides the value, label, checked, other (if checkbox contains `ic-textfield` and disabled state).

Something like (but not exactly):
```jsx
[
    { label: 'item-1', value: 'item-1', disabled: true, other: null, checked: false },
    { label: 'item-2', value: 'item-2', disabled: false, other: null, checked: true },
    { label: 'item-3', value: 'item-3', disabled: false, other: null, checked: true },
]
```

This should be possible by getting the `ic-checkbox-group` to querySelectorAll of the `ic-checkbox` and when an `icCheck` is triggered from one of the checkboxes, `IcCheckboxGroup` is able to retrieve the status of the updated checkbox and update the `icChange` object. 

## 💰 Use value
Providing this object will make it easier for consumers to filter out the checked items. 

## Additional info
N/A

**Comment by GCHQ-Developer-112** [comment]
#581 duplicates this ticket. This is the body of the #581 ticket.

## Summary of the bug
When you have multiple `ic-checkbox` components in `ic-checkbox group` and select a checkbox, the value emitted by the `onIcChange` event updates with the value of the selected checkbox. However, if you unselect the same checkbox, the value emitted by the `onIcChange` event. This is particularly an issue if you try to filter using checkboxes. As the filter works based on the value (event.detail.value) from `onIcChange`.

## 🪜 How to reproduce
For Core Team: see the ICDS test app, run the code and view the following path: "/drinks/about-you"

## 🧐 Expected behaviour
Expect the value in onIcChange when a checkbox is checked AND unchecked i.e. the value should always update and reflect the checkboxes that are currently checked

## 📸 Screenshots or code
Example of how checkboxes have been used as part of a filter
**"Coffee" option checked**
![Screenshot 2023-04-17 at 11 30 38](https://user-images.githubusercontent.com/113986285/232459526-8ef2f775-fee4-4cf9-bd85-915f0c4478fd.png)

**"Coffee" option now unchecked (after being checked)**
![Screenshot 2023-04-17 at 11 30 57](https://user-images.githubusercontent.com/113986285/232459529-08a720ca-9130-4a48-b6bd-36e388a64d85.png)
