### ISSUE TITLE
[ic-stepper]: Issues with responsiveness of `ic-stepper` when stepper used alongside `ic-side-navigation` and `flex-grow` wrapper

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#486]
## Summary of the bug
The resizeObserver method used in `ic-stepper` stops being called if the min-width is met and the wrapper element has `flex-grow:1`.
By `flex-grow` being set on the wrapper, once `ic-stepper` has reached it's min-width, the container will no longer shrink. This prevents the `compact` variant from being set or updating the connector width. **This only happens when reducing the size of the viewport.** Increasing the size of the viewport, increases the size of the wrapper and triggers the resizeObserver.

Another thing to consider is that - if there are a large number of steps, the min-width will increase and `flex-grow` will not reduce the width of the wrapper.

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Copy the following code into a page
```html
<div style='display: flex; height: 100%;'>
      <ic-side-navigation
        app-title="Application Name"
        version="v0.0.0"
        status="BETA"
      >
      </ic-side-navigation>
      <div style='display: flex; flex-direction: column; flex-grow:1;'>
        <main>
          <ic-section-container style='min-height: 100vh' aligned='full-width'>
            <div>
              <div>
                <ic-stepper>
                  <ic-step step-title='one'></ic-step>
                  <ic-step step-title='two'></ic-step>
                  <ic-step step-title='three'></ic-step>
                  <ic-step step-title='four'></ic-step>
                  <ic-step step-title='five'></ic-step>
                </ic-stepper>
              </div>
            </div>
          </ic-section-container>
        </main>
      </div>
    </div>
```
2. Increase the size of the viewport
3. Decrease the viewport

## 🧐 Expected behaviour
Stepper should reduce in width

## 📸 Screenshots or code
![Capture](https://user-images.githubusercontent.com/116016939/225687406-08f6f7c9-e08e-4de8-8c6c-766ee2dfec9d.PNG)

## 🖥 Desktop
 - OS: Windows
 - Browser: Chrome
 - Version: 110

## 📱 Mobile
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Comment by gd2910** [comment]
With investigation this appears to be a nuance with flexbox rather than a bug with ic-stepper. With `display: flex;` set on the parent the child is automatically set to `min-width : auto;` which will grow when expanded (as will ic-stepper) but will not shrink beyond its contents when contracted, ic-stepper will not shrink because by all intents and purposes the parent container is still the same size.

To fix this the container needs to have the` min-width: auto;` unset, either by setting `min-width: 0;` or `width: 100%;`

Another ticket has been raised to question the need for a design pattern in ic-stepper code examples to show this; https://github.com/mi6/ic-design-system/issues/541
