### ISSUE TITLE
IcTextField should pass all other props available to input components and check for other components

### ISSUE THREAD

**Issue by MI6-651** [mi6/ic-ui-kit#503]
## Summary
IcTextField only passes down some properties, it should pass down all other properties as well into the input component.

Specifically this ticket will add any properties to TextField not currently available, but will not retrospectively add the hidden aria props (that are available, just hidden). 

## 💰 Use value
This is useful as it provides more options for developers, as it adds functionality e.g. validation on browser date pickers with an ICDS text field.

**Comment by ad9242** [comment]
Rather than exposing as props, could potentially be implemented the way that aria attributes are inherited currently, i.e. have a list of the supported attributes. 
Technically would not be a breaking change if we wanted to change the existing props to this method, as they could still be set on the component, just not documented as props

**Comment by ad9242** [comment]
Following on from previous comment - the decision is to use props

**Comment by MI6-255** [comment]
https://github.com/mi6/ic-ui-kit/issues/515
