### ISSUE TITLE
In VoiceControl, open top navigation in mobile, you cannot select any pages

### ISSUE THREAD

**Issue by ASM995** [mi6/ic-ui-kit#592]
## Summary of the bug
Top Navigation burger menu does not allow you to select pages using iOS Voice Control. 

## 🪜 How to reproduce
Turn on iOS Voice Control, select top navigation burger, no option to select pages

## 🧐 Expected behaviour
A way to select pages.

## 📸 Screenshots or code
If you can, add screenshots to show the problem. If you need to show a code example, you can include a snippet or link to a repository with an example.

## 🖥 Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

## 📱 Mobile
 - Device: iPhone XR
 - Browser: Safari
 - Version: [e.g. 22]

## Additional info
Tell us anything else useful to help us fix or understand the problem.

**Comment by GCHQ-Developer-847** [comment]
Cannot reproduce

To explain in more detail, this bug was that the navigation items on the top nav were not displaying the number overlays which Voice Control users often use to select different clickable items on a page (but they eventually appear after navigating around a few different pages).

This bug was occurring when testing with an actual iPhone, but it has been checked on Chrome and Safari (using the mobile simulator views in the DevTools of each browser) and this issue is not happening; all items are displaying a number and can be clicked on by the user reading out the associated number.

It does not seem as if there is anything that can be done as it cannot be replicated in a development environment, and it appears to be an iOS bug anyway.

**Comment by GCHQ-Developer-847** [comment]
(See above comment)
