### ISSUE TITLE
IcButton (icon) not being garbage collected

### ISSUE THREAD

**Issue by MI6-651** [mi6/ic-ui-kit#682]
## Summary of the bug
When conditionally rendering IcButtons, with variant='icon', the nodes are not being collected on unmount, causing detached nodes and associated event listeners to remain in memory. This is causing performance issues. This may not necessarily be limited to icon buttons, and could potentially be an issue with other components.

**Comment by GCHQ-Developer-530** [comment]
This is blocked as it appears to be an issue with stencil. Multiple issues have been raised, but the stencil team are focused on v3 and so haven't produced a fix as of yet. https://github.com/ionic-team/stencil/issues?q=is%3Aissue+is%3Aopen+memory+leak

It may be fixed in v3, so this issue may be fixed by #386 for us, but not too sure at the moment.

**Comment by GCHQ-Developer-530** [comment]
Specific workaround for icon buttons is to use disableTooltip prop as this should bring the number of detached nodes down slightly.

**Comment by GCHQ-Developer-530** [comment]
Closing this ticket as the fix would either be upgrade to v3 of stencil (which there is already a ticket for), and if the issue still persists on v3, then we would have to wait until stencil fixes the issue and upgrade to the fixed version.

**Comment by ad9242** [comment]
The work undertaken in https://github.com/mi6/ic-ui-kit/issues/788 should significantly improve the performance of the button\tooltip components. 
There is still an underlying issue in Stencil though, it seems
