### ISSUE TITLE
Your J Title

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-ui-kit#7]
Moving issues into the "Done" column doesn't auto close the issue. We could potentially use an action to auto close issues in the "Done" column and reopen if they are moved out of the "Done" column if necessary

## Why do we need it?
This would make the GitHub experience better for all and make issue management easier

## Additional notes
The [issue states action](https://github.com/marketplace/actions/issue-states) seems like it would fix the issue described above

**Comment by GCHQ-Developer-741** [comment]
Issue states action was created to automate Projects (classic). Since our project is Projects V2 (Beta), there aren't any events to trigger a workflow from this yet (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows).

Found a link to a thread of people having a similar issue, they recommended using the GitHub API (https://github.com/oslokommune/kjoremiljo-admin-issues/issues/41), possibly linking in with the projects_v2_item workflow (https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#projects_v2_item)

**Comment by MI6-255** [comment]
Fixed
