### ISSUE TITLE
[normalize.css]: Review whether normalize is outdated as a CSS reset file

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#718]
## Summary
Normalize.css is the CSS reset used within ICDS but it hasn't been updated for 5 years. This ticket is to review and update to a new CSS reset if normalize.css no longer covers the required styles. 

## 💬 Description
Normalize is used to reset all the browser set styling so there is a better, consistent style across all browsers. At the moment, Normalize has not been updated for 5 years so it is worth while investigating if a more modern, up to date CSS reset file would be more beneficial. 

## 💰 Use value
As browsers develop, more default browser styles may be introduced which Normalize.css does not cover. This could potentially cause styling issues between browsers. By using a more up to date, more recently maintained CSS reset file, there is confidence the CSS reset will cover all bases. 

## Additional info
Tell us anything else useful to help us understand your suggestion.

**Comment by MI6-255** [comment]
Include a guidance change to update the instructions

**Comment by MI6-255** [comment]
Output to be a ticket to action, let me know once done to bring it into sprint

**Comment by GCHQ-Developer-299** [comment]
Did some research about our options:
Do we move to modern-normalize?
Do we stay where we're at and make changes when needed?
Do we remove normalize?

Both modern-normalize and removing normalize introduced display issues in the components and would require changes to per-component or global CSS. 
We decided to not change anything right now, and to keep using normalize.

We understand that changing our approach in future won't be a breaking change since the impact of normalize.css is all scoped inside component CSS files.
