### ISSUE TITLE
[ic-top-navigation] Screen reader reads the navigation items out twice

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#860]
## Summary of the bug
When testing with a screen reader, navigation items in the top nav are read out twice.

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Go to guidance site
2. Turn on screen reader
3. Navigate to navigation items
4. See the error

## 🧐 Expected behaviour
It should only read them out once.

## 📸 Screenshots or code
On our website:
<img width="439" alt="Screenshot 2023-07-05 at 14 55 37" src="https://github.com/mi6/ic-ui-kit/assets/111882034/a253dcea-078e-4433-8893-55eb44ecf84d">
In storybook:
<img width="624" alt="Screenshot 2023-07-05 at 14 49 04" src="https://github.com/mi6/ic-ui-kit/assets/111882034/fc07890f-f042-4a04-8045-a9cc495b3b83">

**Comment by GCHQ-Developer-299** [comment]
From an initial glance, it seems that the issue is an overabundance of aria-labels. If the navigation-item component has a text label, it doesn't need an aria-label. 
`<a slot="navigation-item" href="/get-started" aria-label="Get started">Get started</a>`

Will look to update the navigation-item code

**Comment by GCHQ-Developer-299** [comment]
Looks like it's maybe the aria-described-by tooltips.
ic-buttons, if they are Only Icon, have both a tooltip and an aria-label, which means they too have their names read out twice. Need to make it so that, if there's a tooltip then the aria-label isn't set.

**Comment by GCHQ-Developer-299** [comment]
Re-opening because the issue is still present on navigation items. 
The `<ic-tooltip>` element is still rendered in the shadow-root on navigation-items and is being read out.

To replicate with screenreader: 
- visit ICDS guidance site
- Navigate through elements linearly, do not tab to the navigation items
- You'll find there's an invisible label (the ic-tooltip I think) that reads out, before you navigate to the link which also reads its label

**Comment by GCHQ-Developer-299** [comment]
Reading the mozilla spec for the [tooltip role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role) and I think maybe i've been overcomplicating things. If I can add an aria-describedby to the button, that will meet the spec and maybe silence the double-reading?

**Comment by GCHQ-Developer-299** [comment]
Superceded by https://github.com/mi6/ic-ui-kit/issues/1227
