### ISSUE TITLE
IcButton transparent background causes issue on focus

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#891]
## Summary of the bug
When an IcButton wth `appearance="light"` is focussed there is a slight outline in the corners. Also content from other elements can be seen 

## 🪜 How to reproduce
Focus an IcButton component - see screenshot below showing corners

## 🧐 Expected behaviour
The content behind & outline should not be visible

## 📸 Screenshots or code
![image](https://github.com/mi6/ic-ui-kit/assets/116102637/497f5ecf-2d2a-45b1-8716-480a7ab3fc70)

![image](https://github.com/mi6/ic-ui-kit/assets/116102637/67d6c030-3b84-43dc-964d-572db75e0319)

## Additional info
the fix seems to be to make the background white instead of transparent, but need to ensure that all hover\pressed states still work & dark variant also still work correctly

**Comment by jd239** [comment]
Pagination bar for data table has a grey background so a background colour on the button may not fix the issue.

**Comment by GCHQ-Developer-530** [comment]
Solved the issue of other elements appearing under the button by adding margins around icon buttons, however nothing could be done about slight outline on the corners as this is due to a slight difference in colour between transparent on a white background and the white of the focus border. The background of the button couldn't be changed to white due to reasons @jd239 added above.
